### PR TITLE
Changes for return type ambiguity breaking modification to the compil…

### PR DESCRIPTION
**Pull request by wilsonk**
…er. A couple others for Stdin/Stdout also. Not totally sure that I changed Metronome.zig correctly.

### CODE REVIEW

**Comment by tiehuis** [comment]
Thanks. This looks good. I'm going to wait a few days until I update my compiler and see what other pending breaking changes are planned so I can possibly do them all at once.

**Comment by wilsonk** [comment]
Sounds good :)

**Comment by tiehuis** [comment]
So the ContainerDecl syntax change has now been reverted as of https://github.com/ziglang/zig/pull/1685. There are still a few things here which are good and need changing though so if you removed the ContainerDecl changes I'll happily merge.

**Comment by tiehuis** [comment]
Should have fixed up everything else in https://github.com/tiehuis/zig-rosetta/commit/d58a9d7f5d7667a66ff5571b98523f2ce1f25c7d.

**Pull request closed without merging**
